In [26]:
import torch


class Net(torch.nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.hid1 = torch.nn.Linear(3,3) 
    self.hid2 = torch.nn.Linear(3,1)

  def forward(self, x):
    z = torch.relu(self.hid1(x))
    z = torch.relu(self.hid2(z))
    return z

model = Net()

In [36]:
def loss_function(y, y_hat):
  return torch.mean((y - y_hat)**2)
# Create a tensor
input = torch.tensor([1.0, 2.0, 3.0])
target = torch.tensor([4.0])
model = Net()
print(model.hid1.weight)
print(model.hid1.bias)
print(model.hid2.weight)
print(model.hid2.bias)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss = loss_function
output = model(input)
print(output)
loss_value = loss(output, target)
print(loss_value)
loss_value.backward()
optimizer.step()


Parameter containing:
tensor([[ 0.2077,  0.1458,  0.0724],
        [ 0.3559,  0.0342,  0.5717],
        [-0.1638,  0.3048,  0.1396]], requires_grad=True)
Parameter containing:
tensor([ 0.1399, -0.4112,  0.0286], requires_grad=True)
Parameter containing:
tensor([[ 0.0470, -0.5717, -0.5683]], requires_grad=True)
Parameter containing:
tensor([0.3677], requires_grad=True)
tensor([0.], grad_fn=<ReluBackward0>)
tensor(16., grad_fn=<MeanBackward0>)


In [38]:
torch.autograd.grad(outputs=output, inputs=input)


RuntimeError: One of the differentiated Tensors does not require grad

In [28]:
print(model.hid1.weight.grad)
print(model.hid1.bias.grad)
print(model.hid2.weight.grad)
print(model.hid2.bias.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0., 0.])
tensor([[0., 0., 0.]])
tensor([0.])


In [140]:
x = torch.ones(2,requires_grad=True)  # input tensor
y = torch.zeros(3,requires_grad=True)  # expected output
W = torch.randn(2, 3, requires_grad=True) # weights
# b = torch.randn(3, requires_grad=True) # bias vector
z = torch.matmul(x,W) # output
loss = (z - y).pow(2)
print(W)
# print(b)
print(z)
print(W[0])
# print(W[0].sum())
# print(W[1].sum())
# print(W[0].sum() * 2 * W[0].sum())
# print(2 * W[0].sum() * (z ))
print(loss)
external_grad = torch.tensor([1.,1.,1.,])
loss.backward(gradient=external_grad)
print(x.grad)
print(W.grad)


tensor([[-0.2479, -0.1212, -1.9611],
        [ 1.0857, -1.5598,  1.6598]], requires_grad=True)
tensor([ 0.8378, -1.6809, -0.3013], grad_fn=<SqueezeBackward3>)
tensor([-0.2479, -0.1212, -1.9611], grad_fn=<SelectBackward0>)
tensor([0.7019, 2.8255, 0.0908], grad_fn=<PowBackward0>)
tensor([1.1736, 6.0627])
tensor([[ 1.6755, -3.3619, -0.6026],
        [ 1.6755, -3.3619, -0.6026]])


In [141]:
2 * z[0]  * (W[0][0])

tensor(-0.4154, grad_fn=<MulBackward0>)

In [143]:
z[0] * 2

tensor(1.6755, grad_fn=<MulBackward0>)

In [47]:
loss.backward()
print(W.grad) #OK
print(b.grad) #OK
print(x.grad)
print(y.grad)
print(z.grad) # WARNING
print(loss.grad) # WARNING

tensor([[-0.2960, -0.4942, -0.8776],
        [-0.2960, -0.4942, -0.8776]])
tensor([-0.2960, -0.4942, -0.8776])
None
None
None
None


/var/folders/1g/_wddvqdx1zn1sqjjw3s9m2940000gt/T/ipykernel_22312/63881608.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:485.)
  print(z.grad) # WARNING
/var/folders/1g/_wddvqdx1zn1sqjjw3s9m2940000gt/T/ipykernel_22312/63881608.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tenso